アカウント編集画面の作成
Yuki-TU/point-app-frontend pull request #38
Opened 2023-03-11 00:47 UTC by daikiku10

# 概要

closes #37 

# 変更内容

- アカウント情報画面にアカウント更新画面へ遷移するサイドバーを作成
- アカウント更新画面の作成
# 影響範囲

- アカウント情報画面
# 動作要件

# 補足

2023-03-11 00:56 UTC, daikiku10 commented
@Yuki-TU 
レビューお願いします。
1点だけ、実装未完成のところがあり、詰まっているためまた日程合わせて通話したいです、、。
アカウント更新時に201が正しく返ってきますが、スナックバーが表示されない場合があります。
具体的にはアカウント名を変更せずに更新すると表示され、アカウント名を変更して更新すると表示されません。
どちらも201が返ってきており、toast.tsのsuccessで正しくメッセージが送れていることは確認できました。

2023-03-12 17:18 UTC, Yuki-TU commented
@daikiku10 
フォーマッターがかかっていないですね。。
`$ make format`, `$ make linter`の実行お願いします
また、VSCode使っていたら、ESLintとPrettierの拡張機能を入れて、自動フォーマットONの設定にすると良いと思います！
後、CIで自動検査を入れたいので、以下のタスクもまた時間ある時にお願いします！
https://github.com/hack-31/point-app-frontend/issues/39

2023-03-13 12:15 UTC, daikiku10 commented
@Yuki-TU 
もともと拡張機能を入れて自動フォーマットもONでしたが、make ciをするのを忘れていました、、。
修正しました。
5c18aa327881740100a0301d3d6802f15c19985d

2023-03-13 15:26 UTC, Yuki-TU commented
commit番号の名前が#79になっています

2023-03-13 21:56 UTC, daikiku10 commented
@Yuki-TU 
コミット名修正しました！

2023-03-15 06:02 UTC, Yuki-TU requested changes

2023-03-15 06:02 UTC, Yuki-TU commented on src/features/account/component/accountUpdate.tsx
> +        history("/account");
僕もでなかったので、以下のように、成功したら出すといいかもです
成功しても、その画面に止まってもいいかもしれません。

```ts
          await refetchUser();
          // NOTE: ステータスコード201なので、スナックバー出るはずだが、出ないので、
          // 明示的にスナックバーを表示
          snackbar.success(res.data.message);
```

2023-03-15 23:23 UTC, daikiku10 commented on src/features/account/component/accountUpdate.tsx
> +        history("/account");
@Yuki-TU 
成功後はその画面から遷移しないように修正しました。
709addb34a213f07cc96f8145c636a9424c8e808

2023-03-18 11:22 UTC, Yuki-TU commented on src/features/account/component/accountUpdate.tsx
> +        history("/account");
うーむ、うまく動かないですね。。
@daikiku10 さんの環境では動いています？

2023-03-18 11:34 UTC, daikiku10 commented on src/features/account/component/accountUpdate.tsx
> +        history("/account");
@Yuki-TU 
あれ？動いてたような、、確認します！

2023-03-18 15:33 UTC, Yuki-TU commented on src/features/account/component/accountUpdate.tsx
> +        history("/account");
@daikiku10 
この件、以下のコミット修正しました。
[fix:](https://github.com/hack-31/point-app-frontend/pull/38/commits/8ec9abb8cbff199b39df73b39cfbd21939412147)https://github.com/hack-31/point-app-frontend/issues/37 [refetchした時にtoastifyが消えるバグ修正](https://github.com/hack-31/point-app-frontend/pull/38/commits/8ec9abb8cbff199b39df73b39cfbd21939412147)

根本的な原因としては、toastifyを表示させるのにコンテナコンポーネント`<ToastContainer />`を記述しているのですが、そちらの記述する場所がよくありませんでした。。public.tsxとprotected.tsxの両方に記述していたのですが、こちらを、Providerを記述するapp.tsxに移動させることでうまく動作しました。

なので、ステータスコードが201にするだけでスナックバーは出るようになっていると思うので、ご確認お願いします！

2023-03-18 21:55 UTC, daikiku10 commented on src/features/account/component/accountUpdate.tsx
> +        history("/account");
@Yuki-TU 
ありがとうございます！！
なるほど、Suspenseの外にToastContainerを移動させたのですね！確かにスナックバーが表示されることを確認しました。ありがとうございます！

2023-03-19 09:41 UTC, Yuki-TU approved these changes
LGTM

2023-03-19 09:41 UTC, merged